version: '3'

services: 
  app: 
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - "4200:4200"  #declaring ports to use in the docker container and your application
    volumes:
      - "./:/node-docker-example" #declaring volume in which the application would run inside the docker container
    container_name: app
    command: npm run dev   #command that triggers the application to run