version: '3'

services: 
  api-dev: 
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"  #declaring ports to use in the docker container and your application
    volumes:
      - "./:/node_docker" #declaring volume in which the application would run inside the docker container
    command: npm run dev   #command that triggers the application to run
    

